version: "3"

services:

  miniconda:
    container_name: dmx-miniconda
    hostname: miniconda
    image: dimajix/miniconda:4.5.4
    build: 
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    command: bash
    env_file:
      - docker-compose.env
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}

networks:
  default:
    external:
      name: bridge

